---
port_profiles:

  - profile: IDF1
    mode: "trunk phone"
    spanning_tree_portfast: edge
    spanning_tree_bpduguard: enabled
    native_vlan: 110
    phone_vlan: 120
    phone_trunk_mode: untagged
    dot1x:
      port_control: "force-authorized"
      reauthentication: true
      pae:
        mode: "authenticator"
      host_mode:
        mode: "multi-host"
        multi_host_authenticated: true
      mac_based_authentication:
        enabled: true
      timeout:
        reauth_period: server
        tx_period: 3
      reauthorization_request_limit: 3

  - profile: IDF2
    mode: "trunk phone"
    spanning_tree_portfast: edge
    spanning_tree_bpduguard: enabled
    native_vlan: 210
    phone_vlan: 220
    phone_trunk_mode: untagged
    dot1x:
      port_control: "force-authorized"
      reauthentication: true
      pae:
        mode: "authenticator"
      host_mode:
        mode: "multi-host"
        multi_host_authenticated: true
      mac_based_authentication:
        enabled: true
      timeout:
        reauth_period: server
        tx_period: 3
      reauthorization_request_limit: 3

  - profile: IDF3
    mode: "trunk phone"
    spanning_tree_portfast: edge
    spanning_tree_bpduguard: enabled
    native_vlan: 310
    phone_vlan: 320
    phone_trunk_mode: untagged
    dot1x:
      port_control: "force-authorized"
      reauthentication: true
      pae:
        mode: "authenticator"
      host_mode:
        mode: "multi-host"
        multi_host_authenticated: true
      mac_based_authentication:
        enabled: true
      timeout:
        reauth_period: server
        tx_period: 3
      reauthorization_request_limit: 3

